### ISSUE TITLE
documentation for isInternal property

### ISSUE THREAD

**Issue by mcferren** [ng-dnd/ng-dnd#10]
can you please point me to more information to explain what item.isInternal represents? 

I am getting a true value everywhere I use it

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/1240601/189539107-e602f716-670d-45d0-900e-a0be206b746a.png">

**Comment by mcferren** [comment]
* getting a true value everywhere I console.log it, including hovering over a lower index of existing parent or hovering over a separate parent

**Comment by nzbin** [comment]
I'm sorry, I don't quite understand your issue. You can check out the docs [here](https://ng-dnd.github.io/ng-dnd/).

**Comment by mcferren** [comment]
thank you
