### ISSUE TITLE
Support for Zoneless Mode in ng-dnd

### ISSUE THREAD

**Issue by onkarjit** [ng-dnd/ng-dnd#17]
With Angular 18 scheduled for release this week, we will soon have the option to make our application zoneless by using:

`provideExperimentalZonelessChangeDetection()`

Additionally, we can remove zone.js from our angular.json configuration:

```
"polyfills": [
   "zone.js" <-- Remove This
],
```

However, it appears that `DndService` currently depends on `NgZone`:

![image](https://github.com/ng-dnd/ng-dnd/assets/26631593/32504afb-52c6-4421-8397-c6bcd2b3221b)

While we can use `provideExperimentalZonelessChangeDetection()` with `ng-dnd`, removing `zone.js` from the polyfills array results in the following error:

> Uncaught (in promise) ReferenceError: Zone is not defined
    at new _DndService (ng-dnd-core.mjs:973:20)
    at Object.DndService_Factory [as factory] (ng-dnd-core.mjs:1088:14)
    at core.mjs:3233:47
    at runInInjectorProfilerContext (core.mjs:871:9)
    at R3Injector.hydrate (core.mjs:3232:21)
    at R3Injector.get (core.mjs:3095:33)
    at R3Injector.get (core.mjs:3105:33)
    at ChainedInjector.get (core.mjs:16588:36)
    at lookupTokenUsingModuleInjector (core.mjs:5746:39)
    at getOrCreateInjectable (core.mjs:5794:12)

It would be amazing if `ng-dnd` could work without `zone.js`. This would allow us to fully leverage the new zoneless capabilities of Angular 18. Is there any plan to support zoneless mode in `ng-dnd`, or are there any workarounds currently available?

**Comment by onkarjit** [comment]
@nzbin

**Comment by kukjevov** [comment]
I agree with this, i just updated project where we are using this library and we had to reenable zone.js because of this requirement ;). Looking forward for this update ;).

**Comment by nzbin** [comment]
@kukjevov I'm working on it, maybe release next week.

**Comment by kukjevov** [comment]
@nzbin simply Awesome 👍. Looking forward to IT.

**Comment by nzbin** [comment]
The v4 has released now, please have a try.

**Comment by kukjevov** [comment]
@nzbin Thank you very much, so far it looks that it is working in out project without any problem ;). Nice work. For me this solves the problem :). Thank you again.
