### ISSUE TITLE
custom preview offsets

### ISSUE THREAD

**Issue by RobinKamps** [ng-dnd/ng-dnd#2]
The multibackend dnd-preview-renderer renders the preview with an offset relative to the dragged element and mouse on initial drag movement.
how to archieve that the preview will always render on fixed offset (e.g. x:0 y:0) next to the cursor?
Like: https://github.com/react-dnd/react-dnd/issues/232#issuecomment-504710984
Thank you very much.

**Comment by nzbin** [comment]
I'm really sorry for the late reply. You can create custom draggable layer to achieve it. It's very similar to react-dnd.
Please checkout this online demo [custom draggable layer](https://stackblitz.com/edit/angular-ivy-ej9eef?file=src%2Fapp%2Fcustom-drag-layer%2Fdraggable-box.component.ts).

**Comment by RobinKamps** [comment]
Thank you very much.
