### ISSUE TITLE
errors on sortable directive render with angular-13

### ISSUE THREAD

**Issue by RobinKamps** [ng-dnd/ng-dnd#4]
within angular 13 an error is raised for the nested droplist context on simple-kanban.

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null'. Current value: 'false'.. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (errors.ts:63:9)
    at bindingUpdated (bindings.ts:72:12)
    at ɵɵproperty (property.ts:49:1)
    at KanbanListComponent_ng_template_6_Template (kanban-list.component.html:38:49)
```

even worse, if you drag one item like crazy between the lists often there is another error thrown:

```
Error in /turbo_modules/@react-dnd/invariant@2.0.0/dist/invariant.cjs.development.js (31:15)
Expected targetIds to be registered.
```

can you please check, if the example works for you with ng-13?

https://stackblitz.com/edit/github-wfbywn

**Comment by nzbin** [comment]
For the first error, you can resolve it with `OnPush` strategy. I have updated your [online demo](https://stackblitz.com/edit/github-wfbywn-l2lz51?file=src%2Fapp%2Fsimple-kanban%2Fcontainer.component.ts).

For the second error, I'm also not sure. Maybe you can check the react-dnd issues.
https://github.com/react-dnd/react-dnd/issues/763

**Comment by nzbin** [comment]
I found it works very well with angular 12, maybe it's not compatible with angular 13. I will update it to angular 13 in the few days.

**Comment by RobinKamps** [comment]
Thank you very much - OnPush does resolve the first part of the issue.
Unfortunatly the second part `Expected targetIds to be registered` is indeed related to nested react-dnd drop targets (and not directly ng-dnd related).
