### ISSUE TITLE
trouble booting examples locally

### ISSUE THREAD

**Issue by mcferren** [ng-dnd/ng-dnd#9]
when I clone and then cd packages/examples and then npm i, I am getting this error

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @ng-dnd/monorepo@0.0.0
npm ERR! Found: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.3.5" from the root project
npm ERR!   peer @angular/common@"13.3.11" from @angular/service-worker@13.3.11
npm ERR!   node_modules/@angular/service-worker
npm ERR!     peerOptional @angular/service-worker@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.4
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~13.3.4" from the root project
npm ERR!       1 more (jest-preset-angular)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"13.3.5" from @angular/platform-browser-dynamic@13.3.5
npm ERR! node_modules/@angular/platform-browser-dynamic
npm ERR!   @angular/platform-browser-dynamic@"~13.3.5" from the root project
npm ERR!   peer @angular/platform-browser-dynamic@">=10.0.0" from jest-preset-angular@11.1.2
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"^11.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/bmcferren/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bmcferren/.npm/_logs/2022-09-11T00_16_37_045Z-debug-0.log

**Comment by nzbin** [comment]
Don't need cd packages/examples, just cd root project

1. `yarn`
2. `lerna run start`

**Comment by mcferren** [comment]
awesome - thank you
